easy_admin:
    site_name: 'Document Manager'
    design:
        assets:
            css:
                - 'stylesheet/admin.css'
            js:
                - 'js/admin/jscolor.min.js'
    entities:
        Folder:
            class: App\Entity\Folder
            controller: App\Controller\EasyAdmin\FolderController
            form:
                fields:
                    - name
                    - documents
            list:
                fields:
                    - { property: name }
                    - { property: 'createdAt', format: 'd/m/Y h:i:s' }
                    - { property: 'updatedAt', format: 'd/m/Y h:i:s' }
        Document:
            class: App\Entity\Document
            controller: App\Controller\DocumentAdminController
            list:
                actions:
                    - { name: 'edit'}
                    - { name: 'download', icon: 'download', label: '' }
                    - { name: 'delete'}
                    - { name: 'send', icon: 'envelope ', label: '' }
                fields:
                    - { property: 'thumbnail', type: 'image' }
                    - name
                    - { property: tags, template: 'EasyAdmin/Document/tags.html.twig' }
                    - { property: 'createdAt', format: 'd/m/Y h:i:s' }
                    - { property: 'updatedAt', format: 'd/m/Y h:i:s' }
            form:
                fields:
                    - name
                    - tags
                    - file
                    - description
        Tag:
            class: App\Entity\Tag
            list:
                fields:
                    - id
                    - name
                    - { property: color, template: 'EasyAdmin/Tag/color.html.twig' }
            form:
                fields:
                    - name
                    - { property: color, type_options: { attr: { class: 'jscolor' } } }
