language: php

php:
  - 7.1

env:
  global:
    - TARGET=test
    - APP_REPORT_ERROR_EMAIL='test@email.com'
    - APP_ENV=prod
    - APP_DEBUG=0

matrix:
  fast_finish: true
  include:
    - php: 7.1

sudo: false

before_install:
  - if [[ -v $DEPENDENCIES ]]; then composer require --no-update $DEPENDENCIES; fi;
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - flags="--ansi --prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress --no-dev"
  - travis_retry composer install $flags

script:
  - php bin/phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email: matthieu.leorat@protonmail.com
