monolog:
    channels: [ 'document', 'tag', 'security', 'exception' ]
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        document:
            type: rotating_file
            level: info
            path: "%kernel.logs_dir%/%kernel.environment%-document.log"
            max_files: 10
            channels: document
        tag:
            type: rotating_file
            level: info
            path: "%kernel.logs_dir%/%kernel.environment%-tag.log"
            max_files: 10
            channels: tag
        security:
            type: rotating_file
            level: info
            path: "%kernel.logs_dir%/%kernel.environment%-security.log"
            max_files: 10
            channels: security
        exception:
            type: rotating_file
            level: info
            path: "%kernel.logs_dir%/%kernel.environment%-exception.log"
            max_files: 10
            channels: exception
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        console:
            type:   console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
        deduplicated:
            type:    deduplication
            handler: swift
        swift:
            type:       swift_mailer
            from_email: "%env(APP_REPORT_ERROR_EMAIL)%"
            to_email:   "%env(APP_REPORT_ERROR_EMAIL)%"
            subject:    'An Error Occurred! %%message%%'
            level:      error
            formatter:  monolog.formatter.html
            content_type: text/html

