easy_admin_bundle:
    resource: "Controller/AdminController.php"
    prefix: /admin
    type: annotation

admin_dashboard:
    path: /dashboard
    defaults: { _controller: 'App\Controller\EasyAdmin\DashboardController::dashboard' }

# Security
login:
    path: /admin/login
    defaults: { _controller: 'App\Controller\Security\SecurityController::login' }
logout:
    path: /admin/logout

api_login:
    path: /api/login
    defaults: { _controller: 'App\Controller\Api\LoginController::login' }

api_login_check:
    path: /api/login_check

# Resetting
request_password:
    path: /resetting/request-password
    defaults: { _controller: 'App\Controller\Security\ResettingController::requestPassword' }

send_email:
    path: /resetting/send-email
    defaults: { _controller: 'App\Controller\Security\ResettingController::sendEmail' }

check_email:
    path: /resetting/check-email
    defaults: { _controller: 'App\Controller\Security\ResettingController::checkEmail' }

reset_email:
    path: /resetting/reset/{token}
    defaults: { _controller: 'App\Controller\Security\ResettingController::reset' }
